# Generated by Django 4.1 on 2022-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='cash_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
    ]
