# Generated by Django 4.1 on 2022-12-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0002_scores_cash_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='shares_outstanding',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
