# Generated by Django 4.1 on 2022-12-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0003_alter_scores_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webframe.securitylist'),
        ),
    ]
