# Generated by Django 4.1 on 2022-12-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0003_balancesheet_shares_outstanding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financials',
            name='quarterly_close',
        ),
        migrations.RemoveField(
            model_name='financials',
            name='quarterly_variance',
        ),
    ]
