# Generated by Django 4.1 on 2022-12-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0004_alter_scores_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
    ]
