# Generated by Django 4.1 on 2022-12-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0004_remove_financials_quarterly_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='yearly_close',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='yearly_variance',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
