# Generated by Django 3.1.4 on 2021-02-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=50)),
                ('mic', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('ticker', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('figi', models.CharField(max_length=12)),
                ('composite_figi', models.CharField(max_length=12)),
                ('share_class_figi', models.CharField(max_length=12)),
                ('has_invalid_data', models.BooleanField(default=False)),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dividend_amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('split_ratio', models.DecimalField(decimal_places=6, max_digits=10)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('security_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitymeta')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('high', models.DecimalField(decimal_places=6, max_digits=10)),
                ('low', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adj_open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adj_high', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adj_low', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adj_volume', models.IntegerField()),
                ('intraperiod', models.BooleanField(default=False)),
                ('frequency', models.CharField(max_length=16)),
                ('security_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitymeta')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cik', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=50)),
                ('industry_category', models.CharField(max_length=50)),
                ('industry_group', models.CharField(max_length=50)),
                ('company_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('sic', models.CharField(max_length=4)),
                ('employees', models.IntegerField()),
                ('security_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitymeta')),
            ],
        ),
    ]
