# Generated by Django 3.1.4 on 2021-02-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('high', models.DecimalField(decimal_places=6, max_digits=10)),
                ('low', models.DecimalField(decimal_places=6, max_digits=10)),
                ('close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volume', models.IntegerField(default=None, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default=None, max_length=3, null=True)),
                ('symbol', models.CharField(default=None, max_length=12, null=True)),
                ('longname', models.CharField(default=None, max_length=100, null=True)),
                ('country', models.CharField(default=None, max_length=100, null=True)),
                ('sector', models.CharField(default=None, max_length=50, null=True)),
                ('industry', models.CharField(default=None, max_length=50, null=True)),
                ('logo_url', models.CharField(default=None, max_length=100, null=True)),
                ('fulltime_employees', models.IntegerField(default=None, null=True)),
                ('business_summary', models.CharField(default=None, max_length=3000, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('variance', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('PF_score', models.IntegerField(default=None, null=True)),
                ('PF_score_weighted', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('ROA', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('cash', models.IntegerField(default=None, null=True)),
                ('cash_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_ROA', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('accruals', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_long_lev_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_current_lev_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_shares', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_gross_margin', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_asset_turnover', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('research_development', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('effect_of_accounting_charges', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('income_before_tax', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('minority_interest', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('selling_general_administrative', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('other_operating_expenses', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('extraordinary_items', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('non_recurring', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('other_items', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('income_tax_expense', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_operating_expenses', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('cost_of_revenue', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_other_income_expense_net', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('discontinued_operations', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('net_income_from_continuing_ops', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('net_income_applicable_to_common_shares', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dividends', models.DecimalField(decimal_places=6, max_digits=16)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intangible_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_liab', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_stockholder_equity', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_current_liabilities', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_current_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('common_stock', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('other_current_liab', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('other_current_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('other_liab', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('other_stockholder_equity', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('retained_earnings', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('good_will', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('treasury_stock', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('other_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('deferred_long_term_asset_charges', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('deferred_long_term_liab', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('property_plant_equipment', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('long_term_debt', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('long_term_investments', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('net_tangible_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('short_long_term_debt', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('short_term_investments', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('net_receivables', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('accounts_payable', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('capital_surplus', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('minority_interest', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitylist')),
            ],
        ),
    ]
