# Generated by Django 3.1.4 on 2021-02-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='cash_ratio',
            new_name='delta_cash',
        ),
    ]
