# Generated by Django 3.1.4 on 2021-02-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityprice',
            old_name='adj_high',
            new_name='adj_close',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='adj_low',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='adj_open',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='adj_volume',
        ),
    ]
