# Generated by Django 3.1.4 on 2021-02-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymeta',
            name='fulltime_employees',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
