# Generated by Django 3.1.4 on 2021-02-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0002_auto_20210212_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymeta',
            name='fulltime_employees',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
