# Generated by Django 3.1.4 on 2021-02-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0002_auto_20210207_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intangible_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_liab', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_stockholder_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_current_liab', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('common_stock', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_current_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retained_earnings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_liab', models.DecimalField(decimal_places=2, max_digits=15)),
                ('good_will', models.DecimalField(decimal_places=2, max_digits=15)),
                ('treasury_stock', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_current_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deferred_long_term_asset_charges', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_long_term_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_stockholder_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('property_plant_equipment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_current_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_term_investments', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_tangible_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_term_investments', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_receivables', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_term_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accounts_payable', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dividends', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('research_development', models.DecimalField(decimal_places=2, max_digits=15)),
                ('effect_of_accounting_charges', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_before_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minority_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_general_administrative', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_operating_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extraordinary_items', models.DecimalField(decimal_places=2, max_digits=15)),
                ('non_recurring', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_items', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_tax_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_operating_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_of_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_other_income_expense_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discontinued_operations', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income_from_continuing_ops', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income_applicable_to_common_shares', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='security_id',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='mic',
        ),
        migrations.RemoveField(
            model_name='securitymeta',
            name='composite_figi',
        ),
        migrations.RemoveField(
            model_name='securitymeta',
            name='figi',
        ),
        migrations.RemoveField(
            model_name='securitymeta',
            name='has_invalid_data',
        ),
        migrations.RemoveField(
            model_name='securitymeta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='securitymeta',
            name='share_class_figi',
        ),
        migrations.RemoveField(
            model_name='securitymeta',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='intraperiod',
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='category',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='company_url',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='employees',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='industry',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='longname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='sector',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='securitymeta',
            name='symbol',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='currency',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
        migrations.AddField(
            model_name='financials',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitymeta'),
        ),
        migrations.AddField(
            model_name='dividends',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitymeta'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webface.securitymeta'),
        ),
    ]
