# Generated by Django 3.1.4 on 2021-02-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0002_auto_20210213_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dividends',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
