# Generated by Django 3.1.4 on 2021-02-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0003_auto_20210212_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='delta_current_leverage_ratio',
            new_name='delta_current_lev_ratio',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='delta_long_leverage_ratio',
            new_name='delta_long_lev_ratio',
        ),
    ]
