# Generated by Django 3.1.4 on 2021-02-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0003_auto_20210207_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitymeta',
            name='exchange_id',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
