# Generated by Django 3.1.4 on 2021-02-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0003_auto_20210214_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividends',
            name='dividends',
            field=models.DecimalField(decimal_places=6, max_digits=16, null=True),
        ),
    ]
