# Generated by Django 3.1.4 on 2021-02-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0004_auto_20210207_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymeta',
            name='description',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
