# Generated by Django 3.1.4 on 2021-02-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0005_auto_20210208_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymeta',
            name='category',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='company_url',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='country',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='currency',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='description',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='employees',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='industry',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='longname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='sector',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitymeta',
            name='symbol',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
