# Generated by Django 3.1.7 on 2021-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0005_auto_20210221_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='EPS',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='PE_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
    ]
