# Generated by Django 3.1.7 on 2021-02-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0006_auto_20210221_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financials',
            old_name='quarterly_price',
            new_name='quarterly_close',
        ),
    ]
