# Generated by Django 3.1.7 on 2021-02-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0007_auto_20210221_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='variance',
        ),
    ]
