# Generated by Django 3.1.4 on 2021-02-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0007_auto_20210208_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitymeta',
            old_name='longbusinesssummary',
            new_name='business_summary',
        ),
        migrations.RenameField(
            model_name='securitymeta',
            old_name='fulltimeemployees',
            new_name='fulltime_employees',
        ),
    ]
