# Generated by Django 3.1.4 on 2021-02-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0008_auto_20210208_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
            ],
        ),
    ]
