# Generated by Django 3.1.7 on 2021-02-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0008_remove_scores_variance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='cash',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
