# Generated by Django 3.1.4 on 2021-02-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0010_auto_20210209_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='security_id',
            new_name='security',
        ),
        migrations.RenameField(
            model_name='dividends',
            old_name='security_id',
            new_name='security',
        ),
        migrations.RenameField(
            model_name='financials',
            old_name='security_id',
            new_name='security',
        ),
        migrations.RenameField(
            model_name='securityprice',
            old_name='security_id',
            new_name='security',
        ),
    ]
