# Generated by Django 3.1.4 on 2021-02-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0011_auto_20210209_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprice',
            name='volume',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
