# Generated by Django 3.1.4 on 2021-02-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0013_auto_20210210_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymeta',
            name='business_summary',
            field=models.CharField(default=None, max_length=3000, null=True),
        ),
    ]
