# Generated by Django 3.1.4 on 2021-02-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0014_auto_20210210_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitymeta',
            name='category',
        ),
    ]
