# Generated by Django 3.1.4 on 2021-02-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0016_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='security',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webface.securitymeta'),
            preserve_default=False,
        ),
    ]
