# Generated by Django 3.1.4 on 2021-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0017_scores_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='PF_score',
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='accounts_payable',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='capital_surplus',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='common_stock',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='deferred_long_term_asset_charges',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='deferred_long_term_liab',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='good_will',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='intangible_assets',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='inventory',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='long_term_debt',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='long_term_investments',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='minority_interest',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='net_receivables',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='net_tangible_assets',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_assets',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_current_assets',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_current_liab',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_liab',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_stockholder_equity',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='property_plant_equipment',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='retained_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='short_long_term_debt',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='short_term_investments',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_current_assets',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_current_liabilities',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_liab',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_stockholder_equity',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='treasury_stock',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='dividends',
            name='dividends',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='financials',
            name='cost_of_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='discontinued_operations',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='ebit',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='effect_of_accounting_charges',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='extraordinary_items',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='income_before_tax',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='income_tax_expense',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='interest_expense',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='minority_interest',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='net_income',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='net_income_applicable_to_common_shares',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='net_income_from_continuing_ops',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='non_recurring',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='operating_income',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='other_items',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='other_operating_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='research_development',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='selling_general_administrative',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='total_operating_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='total_other_income_expense_net',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='PF_score_weighted',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='ROA',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='accruals',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='cash',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='cash_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_ROA',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_asset_turnover',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_current_leverage_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_gross_margin',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_long_leverage_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_shares',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='variance',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
    ]
