# Generated by Django 3.1.4 on 2021-02-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0018_auto_20210212_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='PF_score',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
    ]
