# Generated by Django 4.1 on 2022-12-16 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0002_rename_first_updated_securitylist_first_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='webframe.securitylist'),
        ),
    ]
