# Generated by Django 4.1 on 2022-12-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0005_remove_portfolio_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dividends',
        ),
    ]
