# Generated by Django 4.1 on 2023-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0007_fundamentals_remove_financials_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentals',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
