# Generated by Django 4.1 on 2023-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0008_fundamentals_gross_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentals',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
