# Generated by Django 4.1 on 2023-01-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0009_fundamentals_total_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundamentals',
            old_name='total_current_assets',
            new_name='current_assets',
        ),
        migrations.RenameField(
            model_name='fundamentals',
            old_name='total_current_liabilities',
            new_name='current_liabilities',
        ),
        migrations.RenameField(
            model_name='fundamentals',
            old_name='total_liab',
            new_name='total_liabilities',
        ),
    ]
