# Generated by Django 4.1 on 2022-12-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitylist',
            old_name='first_updated',
            new_name='first_created',
        ),
    ]
