# Generated by Django 5.1.5 on 2025-02-02 21:25

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2010, 1, 1))),
                ('investment_amount', models.FloatField(default=10000)),
                ('FScore_threshold', models.IntegerField(default=6)),
                ('objective', models.CharField(choices=[('max_sharpe', 'Maximum Sharpe Ratio'), ('min_volatility', 'Minimum Volatility'), ('max_quadratic_utility', 'Maximum Quadratic Utility')], default='max_sharpe', max_length=24)),
                ('estimation_method', models.CharField(choices=[('nn', 'Neural Net'), ('lm', 'Linear Regression')], default='max_sharpe', max_length=16)),
                ('l2_gamma', models.FloatField(default=2)),
                ('risk_aversion', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'db_table': 'data_settings',
            },
        ),
        migrations.CreateModel(
            name='SecurityList',
            fields=[
                ('symbol', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(default=None, null=True)),
                ('country', models.CharField(default=None, null=True)),
                ('sector', models.CharField(default=None, null=True)),
                ('industry', models.CharField(default=None, null=True)),
                ('fulltime_employees', models.IntegerField(default=None, null=True)),
                ('business_summary', models.TextField(default=None, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'security_list',
            },
        ),
        migrations.CreateModel(
            name='Fundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('year', models.IntegerField(default=None, null=True)),
                ('quarter', models.IntegerField(default=None, null=True)),
                ('period_type', models.CharField()),
                ('net_income', models.BigIntegerField(default=None, null=True)),
                ('net_income_common_stockholders', models.BigIntegerField(default=None, null=True)),
                ('total_liabilities_net_minority_interest', models.BigIntegerField(default=None, null=True)),
                ('total_assets', models.BigIntegerField(default=None, null=True)),
                ('current_assets', models.BigIntegerField(default=None, null=True)),
                ('current_liabilities', models.BigIntegerField(default=None, null=True)),
                ('capital_stock', models.BigIntegerField(default=None, null=True)),
                ('cash_and_cash_equivalents', models.BigIntegerField(default=None, null=True)),
                ('gross_profit', models.BigIntegerField(default=None, null=True)),
                ('total_revenue', models.BigIntegerField(default=None, null=True)),
                ('currency_code', models.CharField(default=None, max_length=3, null=True)),
                ('enterprise_value', models.BigIntegerField(default=None, null=True)),
                ('enterprises_value_ebitda_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('enterprises_value_revenue_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('forward_pe_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('market_cap', models.BigIntegerField(default=None, null=True)),
                ('pb_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('peg_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('ps_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist')),
            ],
            options={
                'db_table': 'fundamentals',
                'unique_together': {('symbol', 'as_of_date', 'period_type', 'currency_code')},
            },
        ),
        migrations.CreateModel(
            name='ExpectedReturns',
            fields=[
                ('fundamentals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio_optimizer_webapp.fundamentals')),
                ('last_close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('forecasted_close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('expected_return', models.DecimalField(decimal_places=6, max_digits=16)),
                ('variance', models.FloatField(default=None, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist')),
            ],
            options={
                'db_table': 'expected_returns',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('fundamentals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio_optimizer_webapp.fundamentals')),
                ('allocation', models.DecimalField(decimal_places=6, max_digits=10)),
                ('shares', models.IntegerField()),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('fundamentals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio_optimizer_webapp.fundamentals')),
                ('roa', models.FloatField(default=None, null=True)),
                ('delta_cash', models.FloatField(default=None, null=True)),
                ('delta_roa', models.FloatField(default=None, null=True)),
                ('accruals', models.FloatField(default=None, null=True)),
                ('delta_long_lev_ratio', models.FloatField(default=None, null=True)),
                ('delta_current_lev_ratio', models.FloatField(default=None, null=True)),
                ('delta_shares', models.FloatField(default=None, null=True)),
                ('delta_gross_margin', models.FloatField(default=None, null=True)),
                ('delta_asset_turnover', models.FloatField(default=None, null=True)),
                ('cash_ratio', models.FloatField(default=None, null=True)),
                ('eps', models.FloatField(default=None, null=True)),
                ('book_value', models.BigIntegerField(default=None, null=True)),
                ('pf_score', models.IntegerField(default=None, null=True)),
                ('pf_score_weighted', models.FloatField(default=None, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('open', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('high', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('low', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('close', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('adjclose', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('dividends', models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True)),
                ('splits', models.BigIntegerField(default=None, null=True)),
                ('volume', models.BigIntegerField(default=None, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist')),
            ],
            options={
                'db_table': 'security_price',
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
