# Generated by Django 5.0.6 on 2024-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylist',
            name='last_updated',
            field=models.DateTimeField(default=None),
        ),
    ]
