# Generated by Django 5.0.6 on 2024-07-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0002_fundamentals_enterprise_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentals',
            name='enterprises_value_ebitda_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentals',
            name='enterprises_value_revenue_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentals',
            name='forward_pe_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentals',
            name='pb_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentals',
            name='pe_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentals',
            name='peg_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentals',
            name='ps_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='cash_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_current_lev_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_long_lev_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='eps',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='pe_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='pf_score_weighted',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
    ]
