# Generated by Django 4.2.16 on 2024-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0002_alter_scores_book_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprice',
            name='dividends',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='securityprice',
            name='splits',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='adjclose',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
    ]
