# Generated by Django 5.0.6 on 2024-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0002_alter_securitylist_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylist',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
