# Generated by Django 5.0.6 on 2024-07-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0003_alter_fundamentals_enterprises_value_ebitda_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentals',
            name='accruals',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='cash',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='cash_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='delta_asset_turnover',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='delta_cash',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='delta_current_lev_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='delta_gross_margin',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='delta_long_lev_ratio',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='delta_roa',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='delta_shares',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='eps',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='pf_score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='pf_score_weighted',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='roa',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
