# Generated by Django 5.0.6 on 2024-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0003_alter_securitylist_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylist',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
