# Generated by Django 4.2.16 on 2024-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0004_alter_securityprice_close_alter_securityprice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprice',
            name='splits',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='volume',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
