# Generated by Django 5.1.3 on 2024-11-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0004_fundamentals_accruals_fundamentals_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentals',
            name='accruals',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='cash_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='delta_asset_turnover',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='delta_cash',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='delta_current_lev_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='delta_gross_margin',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='delta_long_lev_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='delta_roa',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='delta_shares',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='pf_score',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='pf_score_weighted',
        ),
        migrations.RemoveField(
            model_name='fundamentals',
            name='roa',
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('fundamentals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio_optimizer_webapp.fundamentals')),
                ('as_of_date', models.DateField()),
                ('period_type', models.CharField()),
                ('pf_score', models.IntegerField(default=None, null=True)),
                ('pf_score_weighted', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('eps', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('roa', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('cash', models.BigIntegerField(default=None, null=True)),
                ('cash_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_cash', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_roa', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('accruals', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_long_lev_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_current_lev_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_shares', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_gross_margin', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_asset_turnover', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist')),
            ],
        ),
    ]
