# Generated by Django 4.2.16 on 2024-11-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0005_remove_fundamentals_accruals_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scores',
            table='scores',
        ),
    ]
