# Generated by Django 4.2.16 on 2025-01-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0005_alter_securityprice_splits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprice',
            name='adjclose',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='close',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='high',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='low',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='open',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True),
        ),
    ]
