# Generated by Django 4.2.16 on 2025-01-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0006_alter_securityprice_adjclose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedReturns',
            fields=[
                ('fundamentals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio_optimizer_webapp.fundamentals')),
                ('last_close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('forecasted_close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('expected_return', models.DecimalField(decimal_places=6, max_digits=16)),
                ('variance', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
            ],
            options={
                'db_table': 'expected_returns',
            },
        ),
    ]
