# Generated by Django 4.2.16 on 2025-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0007_expectedreturns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedreturns',
            name='variance',
            field=models.FloatField(default=None, null=True),
        ),
    ]
