# Generated by Django 4.2.16 on 2025-01-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0008_alter_expectedreturns_variance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='accruals',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='cash_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_asset_turnover',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_cash',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_current_lev_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_gross_margin',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_long_lev_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_roa',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='delta_shares',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='eps',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='pf_score_weighted',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='roa',
            field=models.FloatField(default=None, null=True),
        ),
    ]
