# Generated by Django 4.2.16 on 2025-01-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0009_alter_scores_accruals_alter_scores_cash_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='fundamentals',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio_optimizer_webapp.fundamentals'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='allocation',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='shares',
            field=models.IntegerField(),
        ),
    ]
