# Generated by Django 4.2.16 on 2025-01-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0010_remove_portfolio_fiscal_year_remove_portfolio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='fundamentals',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio_optimizer_webapp.fundamentals'),
        ),
    ]
