# Generated by Django 4.2.16 on 2025-01-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0011_alter_portfolio_fundamentals'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedreturns',
            name='symbol',
            field=models.ForeignKey(db_column='symbol', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='symbol',
            field=models.ForeignKey(db_column='symbol', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist'),
        ),
        migrations.AddField(
            model_name='scores',
            name='symbol',
            field=models.ForeignKey(db_column='symbol', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer_webapp.securitylist'),
        ),
    ]
