# Generated by Django 4.2.16 on 2025-01-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0015_alter_expectedreturns_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentals',
            name='quarter',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
