# Generated by Django 4.2.16 on 2025-01-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer_webapp', '0016_fundamentals_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentals',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
