# Generated by Django 4.1.7 on 2023-04-05 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2010, 1, 1))),
                ('investment_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, max_length=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_created', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(default=None, max_length=100, null=True)),
                ('sector', models.CharField(default=None, max_length=50, null=True)),
                ('industry', models.CharField(default=None, max_length=50, null=True)),
                ('logo_url', models.CharField(default=None, max_length=100, null=True)),
                ('fulltime_employees', models.IntegerField(default=None, null=True)),
                ('business_summary', models.CharField(default=None, max_length=3000, null=True)),
                ('has_fundamentals', models.BooleanField(default=False)),
                ('has_securityprice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('high', models.DecimalField(decimal_places=6, max_digits=10)),
                ('low', models.DecimalField(decimal_places=6, max_digits=10)),
                ('close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adjclose', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volume', models.IntegerField(default=None, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('pf_score', models.IntegerField(default=None, null=True)),
                ('pf_score_weighted', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('eps', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('roa', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('cash', models.BigIntegerField(default=None, null=True)),
                ('cash_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_cash', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_roa', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('accruals', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_long_lev_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_current_lev_ratio', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_shares', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_gross_margin', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('delta_asset_turnover', models.DecimalField(decimal_places=6, default=None, max_digits=16, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('shares', models.IntegerField(default=None, null=True)),
                ('year', models.IntegerField(default=None, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer.securitylist')),
            ],
        ),
        migrations.CreateModel(
            name='Fundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('fiscal_year', models.IntegerField(default=None, null=True)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('net_income_common_stockholders', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('current_assets', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('current_liabilities', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('shares_outstanding', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_optimizer.securitylist')),
            ],
        ),
    ]
