# Generated by Django 4.1.7 on 2023-04-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='fiscal_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
