# Generated by Django 4.1 on 2023-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettings',
            name='risk_aversion',
            field=models.FloatField(default=1),
        ),
    ]
