# Generated by Django 4.1.7 on 2023-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimizer', '0004_scores_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
